### ISSUE TITLE
[FeatureRequest] Make PlaySpeed persistent

### ISSUE THREAD

**Issue by riconeitzel** [mage2tv/issues#22]
If you select "play speed: 2x" in the video player and you have auto play turned on or select another video from the list, the play speed is reset to 1x.

1. It would be great to start the new video with 2x as well
2. It would be great to have a account setting for "preferred play speed"

**Comment by Vinai** [comment]
Thanks, great feedback and good idea I appreciate it! I think that should be possible...

**Comment by Vinai** [comment]
Implemented and deployed within a couple of minutes.
Instead of having a preference in the account the last selected playback rate is persisted in local storage and applied to any subsequent video.

Thanks again for the idea 👍 

Please note I haven't yet worked on the styling issue if autoplay is enabled and the transition happens in full-screen mode.
