### ISSUE TITLE
Not able to register - Contact not associated with account

### ISSUE THREAD

**Issue by AtelierIT** [mage2tv/issues#25]
I'm trying to register but i get "Contact not associated with account" alert

![image](https://user-images.githubusercontent.com/3851709/40203806-18d9c44e-5a2f-11e8-9c8b-9ebfed9b6f4a.png)

**Comment by Vinai** [comment]
Hi, thanks for opening the issue.
The error happens when the account email confirmation is initialized, if the contact email is not associated with any account. The system should not be able to get into that state...
Can you please email me the address you where registering with at contact@mage2.tv so I can check what happened?
Thank you!

**Comment by Vinai** [comment]
Ah, never mind - I think I've got it.
Checking what happened now.

**Comment by Vinai** [comment]
The problem occurs if the email contains upper case characters.
Working on a fix.

**Comment by Vinai** [comment]
Too tired today - please feel free to register with a lower-case email address in the meantime or otherwise you will have to wait until I'm able to complete the task tomorrow. Sorry for the inconvenience!

**Comment by Vinai** [comment]
I'm deploying a quick fix right now. I haven't checked thoroughly that I got all cases, but at least you will be able to register and use the site now, regardless wether there is an upper case letter in the email address.
If such an issue happens again please let us know! Thanks!

**Comment by AtelierIT** [comment]
Super! it works :)
